// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'buttons': string;
  'canvas': string;
  'canvas-container': string;
  'down': string;
  'down-left': string;
  'down-right': string;
  'left': string;
  'overlayed-canvas': string;
  'right': string;
  'up': string;
  'up-left': string;
  'up-right': string;
}
export const cssExports: CssExports;
export default cssExports;
